version: '3'

services:

  mysql:
    image: mariadb:latest
    container_name: funix_api_db
    volumes:
      - db_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - funixweb
    ports:
      - "3306:3306"

networks:
  funixweb:
    driver: bridge

volumes:
  db_data: {}